// Portfolio Theme Configurations
// Each theme defines colors used throughout the portfolio

export interface ThemeConfig {
    id: string;
    name: string;
    description: string;
    // Primary gradient for headings, buttons, accents
    primaryGradient: string;
    primaryGradientHover: string;
    // Accent color for highlights
    accentColor: string;
    accentColorHover: string;
    // Text accent color
    textAccent: string;
    // Button text color (for primary buttons)
    buttonText: string;
    // Timeline dot color
    timelineDot: string;
    // Glowing orb colors (background effects)
    orb1: string;
    orb2: string;
    // Shadow color for buttons
    shadowColor: string;
}

export const themes: Record<string, ThemeConfig> = {
    violet: {
        id: 'violet',
        name: 'Violet Dreams',
        description: 'Classic purple and violet tones',
        primaryGradient: 'from-violet-600 to-purple-600',
        primaryGradientHover: 'from-violet-500 to-purple-500',
        accentColor: 'bg-violet-600',
        accentColorHover: 'bg-violet-500',
        textAccent: 'text-violet-400',
        buttonText: 'text-white',
        timelineDot: 'bg-violet-500',
        orb1: 'bg-violet-600/20',
        orb2: 'bg-purple-600/20',
        shadowColor: 'shadow-purple-500/25',
    },
    ocean: {
        id: 'ocean',
        name: 'Ocean Breeze',
        description: 'Cool cyan and blue waves',
        primaryGradient: 'from-cyan-600 to-blue-600',
        primaryGradientHover: 'from-cyan-500 to-blue-500',
        accentColor: 'bg-cyan-600',
        accentColorHover: 'bg-cyan-500',
        textAccent: 'text-cyan-400',
        buttonText: 'text-white',
        timelineDot: 'bg-cyan-500',
        orb1: 'bg-cyan-600/20',
        orb2: 'bg-blue-600/20',
        shadowColor: 'shadow-blue-500/25',
    },
    sunset: {
        id: 'sunset',
        name: 'Sunset Glow',
        description: 'Warm orange and pink hues',
        primaryGradient: 'from-orange-500 to-pink-600',
        primaryGradientHover: 'from-orange-400 to-pink-500',
        accentColor: 'bg-orange-500',
        accentColorHover: 'bg-orange-400',
        textAccent: 'text-orange-400',
        buttonText: 'text-white',
        timelineDot: 'bg-orange-500',
        orb1: 'bg-orange-600/20',
        orb2: 'bg-pink-600/20',
        shadowColor: 'shadow-orange-500/25',
    },
    forest: {
        id: 'forest',
        name: 'Forest Mist',
        description: 'Natural emerald and teal greens',
        primaryGradient: 'from-emerald-600 to-teal-600',
        primaryGradientHover: 'from-emerald-500 to-teal-500',
        accentColor: 'bg-emerald-600',
        accentColorHover: 'bg-emerald-500',
        textAccent: 'text-emerald-400',
        buttonText: 'text-white',
        timelineDot: 'bg-emerald-500',
        orb1: 'bg-emerald-600/20',
        orb2: 'bg-teal-600/20',
        shadowColor: 'shadow-emerald-500/25',
    },
    rose: {
        id: 'rose',
        name: 'Rose Garden',
        description: 'Elegant pink and rose tones',
        primaryGradient: 'from-pink-600 to-rose-600',
        primaryGradientHover: 'from-pink-500 to-rose-500',
        accentColor: 'bg-pink-600',
        accentColorHover: 'bg-pink-500',
        textAccent: 'text-pink-400',
        buttonText: 'text-white',
        timelineDot: 'bg-pink-500',
        orb1: 'bg-pink-600/20',
        orb2: 'bg-rose-600/20',
        shadowColor: 'shadow-pink-500/25',
    },
    amber: {
        id: 'amber',
        name: 'Golden Hour',
        description: 'Rich amber and yellow golds',
        primaryGradient: 'from-amber-500 to-yellow-600',
        primaryGradientHover: 'from-amber-400 to-yellow-500',
        accentColor: 'bg-amber-500',
        accentColorHover: 'bg-amber-400',
        textAccent: 'text-amber-400',
        buttonText: 'text-white',
        timelineDot: 'bg-amber-500',
        orb1: 'bg-amber-600/20',
        orb2: 'bg-yellow-600/20',
        shadowColor: 'shadow-amber-500/25',
    },
    // Flat/Minimal themes (no gradients)
    minimal_violet: {
        id: 'minimal_violet',
        name: 'Minimal Violet',
        description: 'Clean, solid violet design',
        primaryGradient: 'from-violet-600 to-violet-600',
        primaryGradientHover: 'from-violet-500 to-violet-500',
        accentColor: 'bg-violet-600',
        accentColorHover: 'bg-violet-500',
        textAccent: 'text-violet-400',
        buttonText: 'text-white',
        timelineDot: 'bg-violet-500',
        orb1: 'bg-violet-600/5',
        orb2: 'bg-violet-600/5',
        shadowColor: 'shadow-violet-500/10',
    },
    minimal_blue: {
        id: 'minimal_blue',
        name: 'Minimal Blue',
        description: 'Clean, solid blue design',
        primaryGradient: 'from-blue-600 to-blue-600',
        primaryGradientHover: 'from-blue-500 to-blue-500',
        accentColor: 'bg-blue-600',
        accentColorHover: 'bg-blue-500',
        textAccent: 'text-blue-400',
        buttonText: 'text-white',
        timelineDot: 'bg-blue-500',
        orb1: 'bg-blue-600/5',
        orb2: 'bg-blue-600/5',
        shadowColor: 'shadow-blue-500/10',
    },
    minimal_emerald: {
        id: 'minimal_emerald',
        name: 'Minimal Emerald',
        description: 'Clean, solid emerald green',
        primaryGradient: 'from-emerald-600 to-emerald-600',
        primaryGradientHover: 'from-emerald-500 to-emerald-500',
        accentColor: 'bg-emerald-600',
        accentColorHover: 'bg-emerald-500',
        textAccent: 'text-emerald-400',
        buttonText: 'text-white',
        timelineDot: 'bg-emerald-500',
        orb1: 'bg-emerald-600/5',
        orb2: 'bg-emerald-600/5',
        shadowColor: 'shadow-emerald-500/10',
    },
    minimal_rose: {
        id: 'minimal_rose',
        name: 'Minimal Rose',
        description: 'Clean, solid rose pink',
        primaryGradient: 'from-rose-600 to-rose-600',
        primaryGradientHover: 'from-rose-500 to-rose-500',
        accentColor: 'bg-rose-600',
        accentColorHover: 'bg-rose-500',
        textAccent: 'text-rose-400',
        buttonText: 'text-white',
        timelineDot: 'bg-rose-500',
        orb1: 'bg-rose-600/5',
        orb2: 'bg-rose-600/5',
        shadowColor: 'shadow-rose-500/10',
    },
    minimal_cyan: {
        id: 'minimal_cyan',
        name: 'Minimal Cyan',
        description: 'Clean, solid cyan blue',
        primaryGradient: 'from-cyan-600 to-cyan-600',
        primaryGradientHover: 'from-cyan-500 to-cyan-500',
        accentColor: 'bg-cyan-600',
        accentColorHover: 'bg-cyan-500',
        textAccent: 'text-cyan-400',
        buttonText: 'text-white',
        timelineDot: 'bg-cyan-500',
        orb1: 'bg-cyan-600/5',
        orb2: 'bg-cyan-600/5',
        shadowColor: 'shadow-cyan-500/10',
    },
    minimal_orange: {
        id: 'minimal_orange',
        name: 'Minimal Orange',
        description: 'Clean, solid orange',
        primaryGradient: 'from-orange-600 to-orange-600',
        primaryGradientHover: 'from-orange-500 to-orange-500',
        accentColor: 'bg-orange-600',
        accentColorHover: 'bg-orange-500',
        textAccent: 'text-orange-400',
        buttonText: 'text-white',
        timelineDot: 'bg-orange-500',
        orb1: 'bg-orange-600/5',
        orb2: 'bg-orange-600/5',
        shadowColor: 'shadow-orange-500/10',
    },
    minimal_red: {
        id: 'minimal_red',
        name: 'Minimal Red',
        description: 'Clean, solid red',
        primaryGradient: 'from-red-600 to-red-600',
        primaryGradientHover: 'from-red-500 to-red-500',
        accentColor: 'bg-red-600',
        accentColorHover: 'bg-red-500',
        textAccent: 'text-red-400',
        buttonText: 'text-white',
        timelineDot: 'bg-red-500',
        orb1: 'bg-red-600/5',
        orb2: 'bg-red-600/5',
        shadowColor: 'shadow-red-500/10',
    },
    minimal_slate: {
        id: 'minimal_slate',
        name: 'Minimal Slate',
        description: 'Clean, solid slate gray',
        primaryGradient: 'from-slate-600 to-slate-600',
        primaryGradientHover: 'from-slate-500 to-slate-500',
        accentColor: 'bg-slate-600',
        accentColorHover: 'bg-slate-500',
        textAccent: 'text-slate-400',
        buttonText: 'text-white',
        timelineDot: 'bg-slate-500',
        orb1: 'bg-slate-600/5',
        orb2: 'bg-slate-600/5',
        shadowColor: 'shadow-slate-500/10',
    },
    // Monochrome themes
    pure_white: {
        id: 'pure_white',
        name: 'Pure White',
        description: 'Clean monochrome with white accents',
        primaryGradient: 'from-white to-zinc-200',
        primaryGradientHover: 'from-zinc-100 to-zinc-300',
        accentColor: 'bg-white',
        accentColorHover: 'bg-zinc-100',
        textAccent: 'text-white',
        buttonText: 'text-zinc-900',
        timelineDot: 'bg-white',
        orb1: 'bg-white/5',
        orb2: 'bg-zinc-300/5',
        shadowColor: 'shadow-white/20',
    },
    pure_black: {
        id: 'pure_black',
        name: 'Pure Black',
        description: 'Sleek dark with zinc accents',
        primaryGradient: 'from-zinc-700 to-zinc-800',
        primaryGradientHover: 'from-zinc-600 to-zinc-700',
        accentColor: 'bg-zinc-700',
        accentColorHover: 'bg-zinc-600',
        textAccent: 'text-zinc-400',
        buttonText: 'text-white',
        timelineDot: 'bg-zinc-600',
        orb1: 'bg-zinc-700/10',
        orb2: 'bg-zinc-800/10',
        shadowColor: 'shadow-zinc-700/20',
    },
};

export const themeList = Object.values(themes);

export function getTheme(themeId: string): ThemeConfig {
    return themes[themeId] || themes.violet;
}
